If the except clauses are not in the correct order, that might cause some exceptions not to be caught by the most specific handler.
For example, in this piece of code the second except clause is never taken, because the first one
generalizes the exception that will be caught.

    try:
        1 / 0
    except Exception:
        print("exception occurred")
    except ZeroDivisionError:
        print("don't divide numbers by 0!")
      