Exceptions can be bound to a name inside an except clause, using the **as** keyword.
Using a name which already exists somewhere in the enclosing scope will bring nothing
but confusion and it will increase the maintainance burden.

    val = 42

    try:
        ...
    except Exception as val:
        ...